"""Report export service for generating PDF and Excel reports."""
from typing import List, Dict, Any, Optional
from datetime import datetime, date
from io import BytesIO
import json

# Report generation
try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
    OPENPYXL_AVAILABLE = True
except ImportError:
    OPENPYXL_AVAILABLE = False

import logging

logger = logging.getLogger(__name__)


class ReportExportService:
    """Service for exporting reports to PDF and Excel formats."""
    
    def __init__(self):
        self.reportlab_available = REPORTLAB_AVAILABLE
        self.openpyxl_available = OPENPYXL_AVAILABLE
    
    def generate_pdf(
        self,
        title: str,
        headers: List[str],
        data: List[List[Any]],
        summary: Optional[Dict[str, Any]] = None,
        generated_by: Optional[str] = None
    ) -> BytesIO:
        """Generate a PDF report."""
        if not self.reportlab_available:
            raise ImportError("reportlab is not installed. Install with: pip install reportlab")
        
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.5*inch, bottomMargin=0.5*inch)
        elements = []
        styles = getSampleStyleSheet()
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=18,
            spaceAfter=20,
            alignment=TA_CENTER,
            textColor=colors.HexColor('#667eea')
        )
        elements.append(Paragraph(title, title_style))
        
        # Generated info
        info_style = ParagraphStyle('Info', parent=styles['Normal'], fontSize=10, textColor=colors.gray)
        elements.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", info_style))
        if generated_by:
            elements.append(Paragraph(f"Generated by: {generated_by}", info_style))
        elements.append(Spacer(1, 20))
        
        # Summary section
        if summary:
            summary_title = ParagraphStyle('SummaryTitle', parent=styles['Heading2'], fontSize=14)
            elements.append(Paragraph("Summary", summary_title))
            for key, value in summary.items():
                elements.append(Paragraph(f"<b>{key}:</b> {value}", styles['Normal']))
            elements.append(Spacer(1, 20))
        
        # Data table
        if headers and data:
            table_data = [headers] + data
            
            # Calculate column widths
            available_width = 7 * inch
            col_width = available_width / len(headers)
            
            table = Table(table_data, colWidths=[col_width] * len(headers))
            
            # Style the table
            style = TableStyle([
                # Header
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                
                # Data rows
                ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
                ('ALIGN', (0, 1), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
                ('TOPPADDING', (0, 1), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
                
                # Alternating row colors
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
                
                # Grid
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dee2e6')),
            ])
            table.setStyle(style)
            elements.append(table)
        
        doc.build(elements)
        buffer.seek(0)
        return buffer
    
    def generate_excel(
        self,
        title: str,
        headers: List[str],
        data: List[List[Any]],
        summary: Optional[Dict[str, Any]] = None,
        sheet_name: str = "Report"
    ) -> BytesIO:
        """Generate an Excel report."""
        if not self.openpyxl_available:
            raise ImportError("openpyxl is not installed. Install with: pip install openpyxl")
        
        wb = Workbook()
        ws = wb.active
        ws.title = sheet_name
        
        # Styles
        header_font = Font(bold=True, color="FFFFFF")
        header_fill = PatternFill(start_color="667EEA", end_color="667EEA", fill_type="solid")
        header_align = Alignment(horizontal="center", vertical="center")
        
        thin_border = Border(
            left=Side(style='thin'),
            right=Side(style='thin'),
            top=Side(style='thin'),
            bottom=Side(style='thin')
        )
        
        current_row = 1
        
        # Title
        ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(headers) if headers else 3)
        ws.cell(row=1, column=1, value=title)
        ws.cell(row=1, column=1).font = Font(bold=True, size=16, color="667EEA")
        ws.cell(row=1, column=1).alignment = Alignment(horizontal="center")
        current_row += 2
        
        # Summary
        if summary:
            for key, value in summary.items():
                ws.cell(row=current_row, column=1, value=key)
                ws.cell(row=current_row, column=1).font = Font(bold=True)
                ws.cell(row=current_row, column=2, value=str(value))
                current_row += 1
            current_row += 1
        
        # Headers
        if headers:
            for col, header in enumerate(headers, 1):
                cell = ws.cell(row=current_row, column=col, value=header)
                cell.font = header_font
                cell.fill = header_fill
                cell.alignment = header_align
                cell.border = thin_border
            current_row += 1
        
        # Data
        for row_data in data:
            for col, value in enumerate(row_data, 1):
                cell = ws.cell(row=current_row, column=col, value=value)
                cell.border = thin_border
                cell.alignment = Alignment(vertical="center")
            current_row += 1
        
        # Auto-adjust column widths
        for col in range(1, len(headers) + 1 if headers else 4):
            ws.column_dimensions[get_column_letter(col)].width = 15
        
        buffer = BytesIO()
        wb.save(buffer)
        buffer.seek(0)
        return buffer
    
    def generate_csv(
        self,
        headers: List[str],
        data: List[List[Any]]
    ) -> str:
        """Generate a CSV string."""
        import csv
        from io import StringIO
        
        output = StringIO()
        writer = csv.writer(output)
        writer.writerow(headers)
        writer.writerows(data)
        return output.getvalue()


# Singleton instance
report_export_service = ReportExportService()
