# Generated by Django 4.2.28 on 2026-02-09 05:12

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Unique email address used for authentication', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], db_index=True, default='employee', help_text='User role determining permissions', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department the user belongs to', max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hourly billing rate for the user', max_digits=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed project description')),
                ('client', models.CharField(blank=True, help_text='Client or customer name', max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total project budget', max_digits=15)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='planning', help_text='Current project status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Project creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('manager', models.ForeignKey(blank=True, help_text='User responsible for managing this project', limit_choices_to={'role__in': ['admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, help_text='Team members assigned to this project', related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Work session start time')),
                ('end_time', models.DateTimeField(help_text='Work session end time')),
                ('description', models.TextField(blank=True, help_text='Description of work performed')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', help_text='Current approval status', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the timesheet was submitted for approval', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the timesheet was reviewed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('project', models.ForeignKey(help_text='Project this time was logged against', on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='core.project')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Manager who reviewed this timesheet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_timesheets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Employee who logged this time entry', on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timesheet',
                'verbose_name_plural': 'Timesheets',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'status'], name='core_timesh_user_id_616a14_idx'), models.Index(fields=['project', 'status'], name='core_timesh_project_28db58_idx'), models.Index(fields=['start_time', 'end_time'], name='core_timesh_start_t_51da40_idx')],
            },
        ),
    ]
